services:
  - type: web
    name: campusgenie-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: CORS_ORIGIN
        value: https://campusgenie-git-main-naitikshaxmas-projects.vercel.app
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
